export type Segment =
  | 'restaurant'
  | 'bakery'
  | 'snackBar'
  | 'pizzeria'
  | 'iceCreamShop'
  | 'coffee'
  | 'fastFood'
  | 'barbecue'
  | 'japanese'
  | 'brazilian'
  | 'italian'
  | 'chinese'
  | 'mexican'
  | 'arabic'
  | 'bar'
